# Site
repository: totoroyyb/online-resume
# favicon: images/favicon.ico

# Personal info
name: Yibo Yan
title: Software Developer / Students
email: totoroq@outlook.com
phone: "(530) 574 9508"
website: https://dexstudio.cn

# Social links
# twitter_username: facespics
github_username:  totoroyyb
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: ybyan
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Yibo Yan, a student with enthusiasm to ceaselessly embrace new tools, languages, frameworks, and environments as a quick learner.
  I have experience of developing software in the <mark>Universal Windows Platform</mark> and <mark>iOS</mark> platform.
  Currently I am a first-year student with junior standing pursuing Bachelor Degree of Computer Science at University of California, Davis.

  I am learning <mark>Flutter</mark> framework combined wih **Dart**,
  and plan to learn **Natural Language Processing** with <mark>PyTorch</mark> later this year.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Skills & Languages
more_content: | # this will include new lines to allow paragraphs
  **Skills**
    - <mark>C#</mark>              ★★★★★★☆
    - <mark>Python</mark>          ★★★★★★☆
    - <mark>C++</mark>             ★★★★★☆☆
    - <mark>C</mark>               ★★★★☆☆☆
    - <mark>Rust</mark>            ★★★☆☆☆☆
    - <mark>Go</mark>              ★★★☆☆☆☆
    - <mark>XAML</mark>            ★★★★★★☆
    - <mark>Java</mark>            ★★★★☆☆☆
    - <mark>Swift</mark>           ★★★★★☆☆
    - <mark>Dart</mark>            ★★★☆☆☆☆
    - <mark>Flutter</mark>         ★★★☆☆☆☆
    - <mark>UWP Development</mark> ★★★★★★☆
    - <mark>iOS Development</mark> ★★★★☆☆☆

  **Languages**
    - <mark>Chinese</mark> Native
    - <mark>English</mark> Fully Professional

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
